#include "Kasubag.h"




void Kasubag::penomoranSurat()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:0000000000000999 begin
{
}
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:0000000000000999 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
