#include "Pegawai.h"




void Pegawai::cetakSurat()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:0000000000000991 begin
{
}
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:0000000000000991 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
