#include "Surat.h"




void Surat::buatSurat()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:00000000000009A1 begin
{
}
// section -64--88-43-26--3e3fb5eb:154db5939e8:-8000:00000000000009A1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
